id: ICE394AC8
legacy_id: P001752
ocr_import_info:
  bdrc_scan_id: W8LS20192
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T08:35:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:39:56.996263+00:00'
last_modified: 2022-09-04 12:40:01.709418
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS20192
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS20192
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་སྐུ་གསུམ་སྒྲུབ་པའི་བསྙེན་ཡིག་གྲུབ་གཉིས་ནོར་སྟེར།
statistics:
  ocr_word_mean_confidence_index: 0.7043732605459464
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I8LS20194:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS20194
      total_pages: 40
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS20194.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7043732605459464
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
