id: P001752
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20192
  title: བླ་མ་སྐུ་གསུམ་སྒྲུབ་པའི་བསྙེན་ཡིག་གྲུབ་གཉིས་ནོར་སྟེར།
  author: ''
  volumes:
    8e6ae1d5faef4c05a12c958bb1147f4b:
      image_group_id: I8LS20194
      title: ''
      volume_number: 1
      total_pages: 40
